//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblmedicine
{
    public int Medicine_ID { get; set; }
    public string Medicine_Name { get; set; }
    public int Price_Per_Unit { get; set; }
    public int Quantity { get; set; }
    public string Location { get; set; }
    public System.DateTime Expiry_Date { get; set; }
    public Nullable<int> Company_ID { get; set; }
    public string Image { get; set; }
    public string Description { get; set; }

    public virtual tblmedicinecompany tblmedicinecompany { get; set; }
}

public partial class tblmedicinecompany
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblmedicinecompany()
    {
        this.tblmedicines = new HashSet<tblmedicine>();
    }

    public int Company_ID { get; set; }
    public string Company_Name { get; set; }
    public string Company_Contact_Number { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblmedicine> tblmedicines { get; set; }
}

public partial class tblorder
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblorder()
    {
        this.tblorderdetails = new HashSet<tblorderdetail>();
    }

    public int id { get; set; }
    public string firstname { get; set; }
    public string lastname { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string city { get; set; }
    public string postalcode { get; set; }
    public string address { get; set; }
    public Nullable<int> status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblorderdetail> tblorderdetails { get; set; }
}

public partial class tblorderdetail
{
    public int id { get; set; }
    public Nullable<int> orderid { get; set; }
    public string productname { get; set; }
    public string productprice { get; set; }
    public Nullable<int> productquantity { get; set; }
    public string productimage { get; set; }

    public virtual tblorder tblorder { get; set; }
}

public partial class tbluser
{
    public int User_ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Email_Address { get; set; }
    public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    public string Password { get; set; }
    public int Status { get; set; }
    public int Type_ID { get; set; }
    public string Mobile_No { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public Nullable<int> Zip_Code { get; set; }

    public virtual tblusertype tblusertype { get; set; }
}

public partial class tblusertype
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblusertype()
    {
        this.tblusers = new HashSet<tbluser>();
    }

    public int Type_ID { get; set; }
    public string Type_Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbluser> tblusers { get; set; }
}

public partial class Check_Company_Name_Result
{
    public int Company_ID { get; set; }
    public string Company_Name { get; set; }
    public string Company_Contact_Number { get; set; }
}

public partial class Check_ForgotEmail_Result
{
    public int User_ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Email_Address { get; set; }
    public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    public string Password { get; set; }
    public int Status { get; set; }
    public int Type_ID { get; set; }
    public string Mobile_No { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public Nullable<int> Zip_Code { get; set; }
}

public partial class Check_Medicine_Name_Result
{
    public int Medicine_ID { get; set; }
    public string Medicine_Name { get; set; }
    public int Price_Per_Unit { get; set; }
    public int Quantity { get; set; }
    public string Location { get; set; }
    public System.DateTime Expiry_Date { get; set; }
    public Nullable<int> Company_ID { get; set; }
    public string Image { get; set; }
    public string Description { get; set; }
}

public partial class Check_User_Type_Result
{
    public int Type_ID { get; set; }
    public string Type_Name { get; set; }
}

public partial class CheckEmail_Result
{
    public int User_ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Email_Address { get; set; }
    public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    public string Password { get; set; }
    public int Status { get; set; }
    public int Type_ID { get; set; }
    public string Mobile_No { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public Nullable<int> Zip_Code { get; set; }
}

public partial class Display_Order_By_Email_Result
{
    public int id { get; set; }
    public string firstname { get; set; }
    public string lastname { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string city { get; set; }
    public string postalcode { get; set; }
    public string address { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class Display_Order_Detail_Result
{
    public int id { get; set; }
    public Nullable<int> orderid { get; set; }
    public string productname { get; set; }
    public string productprice { get; set; }
    public Nullable<int> productquantity { get; set; }
    public string productimage { get; set; }
}

public partial class Display_Order_Result
{
    public string address { get; set; }
    public string city { get; set; }
    public string email { get; set; }
    public string firstname { get; set; }
    public int id { get; set; }
    public string lastname { get; set; }
    public string phone { get; set; }
    public string postalcode { get; set; }
    public string Status { get; set; }
}

public partial class DoLogin_Result
{
    public int User_ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Email_Address { get; set; }
    public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    public string Password { get; set; }
    public int Status { get; set; }
    public int Type_ID { get; set; }
    public string Mobile_No { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public Nullable<int> Zip_Code { get; set; }
}

public partial class DoLoginAdmin_Result
{
    public int User_ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Email_Address { get; set; }
    public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    public string Password { get; set; }
    public int Status { get; set; }
    public int Type_ID { get; set; }
    public string Mobile_No { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public Nullable<int> Zip_Code { get; set; }
}

public partial class Get_Medicine_By_Id_Result
{
    public string Description { get; set; }
    public Nullable<int> Company_ID { get; set; }
    public System.DateTime Expiry_Date { get; set; }
    public string Location { get; set; }
    public string Image { get; set; }
    public int Medicine_ID { get; set; }
    public string Medicine_Name { get; set; }
    public int Price_Per_Unit { get; set; }
    public int Quantity { get; set; }
    public string Company_Name { get; set; }
}

public partial class Get_Medicine_Company_Result
{
    public int Company_ID { get; set; }
    public string Company_Name { get; set; }
    public string Company_Contact_Number { get; set; }
}

public partial class Get_Medicine_Result
{
    public string Description { get; set; }
    public Nullable<int> Company_ID { get; set; }
    public System.DateTime Expiry_Date { get; set; }
    public string Location { get; set; }
    public string Image { get; set; }
    public int Medicine_ID { get; set; }
    public string Medicine_Name { get; set; }
    public int Price_Per_Unit { get; set; }
    public int Quantity { get; set; }
    public string Company_Name { get; set; }
}

public partial class Get_Order_ID_Result
{
    public int id { get; set; }
    public string firstname { get; set; }
    public string lastname { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string city { get; set; }
    public string postalcode { get; set; }
    public string address { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class Get_User_Type_Result
{
    public int Type_ID { get; set; }
    public string Type_Name { get; set; }
}

public partial class Get_Users_Result
{
    public string State { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public Nullable<int> Zip_Code { get; set; }
    public int User_ID { get; set; }
    public string Password { get; set; }
    public int Type_ID { get; set; }
    public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    public string Email_Address { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Mobile_No { get; set; }
    public string Type_Name { get; set; }
    public string Status { get; set; }
}

public partial class Seacrch_Medicine_Result
{
    public string Image { get; set; }
    public Nullable<int> Company_ID { get; set; }
    public System.DateTime Expiry_Date { get; set; }
    public string Location { get; set; }
    public int Medicine_ID { get; set; }
    public string Medicine_Name { get; set; }
    public int Price_Per_Unit { get; set; }
    public int Quantity { get; set; }
    public string Company_Name { get; set; }
}

public partial class Seacrch_User_Type_Result
{
    public int Type_ID { get; set; }
    public string Type_Name { get; set; }
}

public partial class Search_Company_Result
{
    public int Company_ID { get; set; }
    public string Company_Name { get; set; }
    public string Company_Contact_Number { get; set; }
}

public partial class Search_User_Result
{
    public int User_ID { get; set; }
    public string Password { get; set; }
    public int Type_ID { get; set; }
    public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    public string Email_Address { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Mobile_No { get; set; }
    public string Type_Name { get; set; }
    public string Status { get; set; }
}

public partial class Select_Order_By_ID_Result
{
    public string address { get; set; }
    public string city { get; set; }
    public string email { get; set; }
    public string firstname { get; set; }
    public int id { get; set; }
    public string lastname { get; set; }
    public string phone { get; set; }
    public string postalcode { get; set; }
    public string Status { get; set; }
}
