//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class MedicalStoreEntities : DbContext
{
    public MedicalStoreEntities()
        : base("name=MedicalStoreEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblmedicine> tblmedicines { get; set; }
    public virtual DbSet<tblmedicinecompany> tblmedicinecompanies { get; set; }
    public virtual DbSet<tblorder> tblorders { get; set; }
    public virtual DbSet<tblorderdetail> tblorderdetails { get; set; }
    public virtual DbSet<tbluser> tblusers { get; set; }
    public virtual DbSet<tblusertype> tblusertypes { get; set; }

    public virtual ObjectResult<Check_Company_Name_Result> Check_Company_Name(string comanyname)
    {
        var comanynameParameter = comanyname != null ?
            new ObjectParameter("comanyname", comanyname) :
            new ObjectParameter("comanyname", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_Company_Name_Result>("Check_Company_Name", comanynameParameter);
    }

    public virtual ObjectResult<Check_ForgotEmail_Result> Check_ForgotEmail(string email)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_ForgotEmail_Result>("Check_ForgotEmail", emailParameter);
    }

    public virtual ObjectResult<Check_Medicine_Name_Result> Check_Medicine_Name(string meicinename)
    {
        var meicinenameParameter = meicinename != null ?
            new ObjectParameter("meicinename", meicinename) :
            new ObjectParameter("meicinename", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_Medicine_Name_Result>("Check_Medicine_Name", meicinenameParameter);
    }

    public virtual ObjectResult<Check_User_Type_Result> Check_User_Type(string usertype)
    {
        var usertypeParameter = usertype != null ?
            new ObjectParameter("usertype", usertype) :
            new ObjectParameter("usertype", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_User_Type_Result>("Check_User_Type", usertypeParameter);
    }

    public virtual ObjectResult<CheckEmail_Result> CheckEmail(string email)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckEmail_Result>("CheckEmail", emailParameter);
    }

    public virtual int Delet_User_Type(Nullable<int> typeid)
    {
        var typeidParameter = typeid.HasValue ?
            new ObjectParameter("typeid", typeid) :
            new ObjectParameter("typeid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delet_User_Type", typeidParameter);
    }

    public virtual int Delete_Medicine(Nullable<int> medicineid)
    {
        var medicineidParameter = medicineid.HasValue ?
            new ObjectParameter("medicineid", medicineid) :
            new ObjectParameter("medicineid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Medicine", medicineidParameter);
    }

    public virtual int Delete_Medicine_Company(Nullable<int> midicinecompanyid)
    {
        var midicinecompanyidParameter = midicinecompanyid.HasValue ?
            new ObjectParameter("midicinecompanyid", midicinecompanyid) :
            new ObjectParameter("midicinecompanyid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Medicine_Company", midicinecompanyidParameter);
    }

    public virtual int Delete_User(Nullable<int> userid)
    {
        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_User", useridParameter);
    }

    public virtual ObjectResult<Display_Order_Result> Display_Order()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Display_Order_Result>("Display_Order");
    }

    public virtual ObjectResult<Display_Order_By_Email_Result> Display_Order_By_Email(string email)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Display_Order_By_Email_Result>("Display_Order_By_Email", emailParameter);
    }

    public virtual ObjectResult<Display_Order_Detail_Result> Display_Order_Detail(Nullable<int> id)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Display_Order_Detail_Result>("Display_Order_Detail", idParameter);
    }

    public virtual ObjectResult<DoLogin_Result> DoLogin(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoLogin_Result>("DoLogin", emailParameter, passwordParameter);
    }

    public virtual ObjectResult<DoLoginAdmin_Result> DoLoginAdmin(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoLoginAdmin_Result>("DoLoginAdmin", emailParameter, passwordParameter);
    }

    public virtual ObjectResult<Get_Medicine_Result> Get_Medicine()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Medicine_Result>("Get_Medicine");
    }

    public virtual ObjectResult<Get_Medicine_By_Id_Result> Get_Medicine_By_Id(Nullable<int> id)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Medicine_By_Id_Result>("Get_Medicine_By_Id", idParameter);
    }

    public virtual ObjectResult<Get_Medicine_Company_Result> Get_Medicine_Company()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Medicine_Company_Result>("Get_Medicine_Company");
    }

    public virtual ObjectResult<Get_Order_ID_Result> Get_Order_ID(string email)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Order_ID_Result>("Get_Order_ID", emailParameter);
    }

    public virtual ObjectResult<Get_User_Type_Result> Get_User_Type()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Type_Result>("Get_User_Type");
    }

    public virtual ObjectResult<Get_Users_Result> Get_Users()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Users_Result>("Get_Users");
    }

    public virtual ObjectResult<Seacrch_Medicine_Result> Seacrch_Medicine(string medicine)
    {
        var medicineParameter = medicine != null ?
            new ObjectParameter("medicine", medicine) :
            new ObjectParameter("medicine", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Seacrch_Medicine_Result>("Seacrch_Medicine", medicineParameter);
    }

    public virtual ObjectResult<Seacrch_User_Type_Result> Seacrch_User_Type(string usertype)
    {
        var usertypeParameter = usertype != null ?
            new ObjectParameter("usertype", usertype) :
            new ObjectParameter("usertype", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Seacrch_User_Type_Result>("Seacrch_User_Type", usertypeParameter);
    }

    public virtual ObjectResult<Search_Company_Result> Search_Company(string company)
    {
        var companyParameter = company != null ?
            new ObjectParameter("company", company) :
            new ObjectParameter("company", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Company_Result>("Search_Company", companyParameter);
    }

    public virtual ObjectResult<Search_User_Result> Search_User(string name)
    {
        var nameParameter = name != null ?
            new ObjectParameter("name", name) :
            new ObjectParameter("name", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_User_Result>("Search_User", nameParameter);
    }

    public virtual ObjectResult<Select_Order_By_ID_Result> Select_Order_By_ID(Nullable<int> id)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Order_By_ID_Result>("Select_Order_By_ID", idParameter);
    }
}
